[phases.setup]
nixPkgs = ["nodejs_20", "nginx"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx ng build --configuration production"]

[start]
cmd = "npx serve dist/portal-capacitaciones/browser -l 8080"
