[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx ng build --configuration production"]

[start]
cmd = "npx serve dist/portal-capacitaciones/browser -s -l 0.0.0.0:$PORT"
