[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx ng build",
  "ls -la dist/portal-capacitaciones/"
]

[start]
cmd = "npm run serve:ssr:portal-capacitaciones"
